# Generated by Django 4.2.11 on 2026-03-25 10:24

import apps.verifier.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.verifier.models.upload_to)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(help_text='Normalised score between 0.0 and 1.0')),
                ('verdict', models.CharField(choices=[('LIKELY_TRUE', 'Likely True'), ('UNCERTAIN', 'Uncertain'), ('LIKELY_FALSE', 'Likely False'), ('UNVERIFIABLE', 'Unverifiable')], default='UNVERIFIABLE', max_length=20)),
                ('summary', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='verifier.upload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['status'], name='verifier_up_status_9d9308_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['file_type'], name='verifier_up_file_ty_733b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['user', '-uploaded_at'], name='verifier_up_user_id_489589_idx'),
        ),
    ]
